# Lab 4: Logisitic Regression, Support Vector Classification (SVC), and Support Vector Regression (SVR)

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVR, SVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Logistic Regression

In [5]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
X = data. data
Y = data.target

In [8]:
# Shape of X and Y
print("X shape:", X.shape)
print("Y shape:", Y.shape)

X shape: (569, 30)
Y shape: (569,)


In [11]:
# First five rows
# First five rows
df = pd.DataFrame(data.data, columns=data.feature_names)
df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [24]:
# Drop columns
df.drop(['mean perimeter'], axis=1, inplace=True)
df.drop(['mean area'], axis=1, inplace=True)

In [12]:
n_samples, n_features = X.shape
n_classes = len(np.unique(Y))
print("Number of samples:", n_samples)
print("Number of features:", n_features)
print("Number of classes:", n_classes)

Number of samples: 569
Number of features: 30
Number of classes: 2


In [13]:
# Train Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [37]:
# Standardize Features
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
# Train logistic regression model# Train logistic regression model
lr = LogisticRegression()
lr.fit(X_train, Y_train)


e:\__GitHub__Bachelor\cmp364-machine-learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [28]:
# Make predictions
Y_pred = lr.predict(X_test)
print("Predictions:", Y_pred)

Predictions: [0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0
 0 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1
 0 1 1]


In [29]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Model evaluation
accuracy = lr.score(X_test, Y_test)
print("Accuracy:", accuracy)

precision = precision_score(Y_test, lr.predict(X_test))
recall = recall_score(Y_test, lr.predict(X_test))
f1 = f1_score(Y_test, lr.predict(X_test))
cm = confusion_matrix(Y_test, lr.predict(X_test))

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:\n", cm)

Accuracy: 0.9473684210526315
Precision: 0.9459459459459459
Recall: 0.9722222222222222
F1 Score: 0.958904109589041
Confusion Matrix:
 [[38  4]
 [ 2 70]]


In [30]:
# Display the coefficient of the trained model
print("Coefficients (coef_):", lr.coef_)
print("Intercept (intercept_):", lr.intercept_)

Coefficients (coef_): [[ 1.17205771  0.31639713  0.17136439 -0.0100642  -0.04849856 -0.21908729
  -0.30751361 -0.12802328 -0.08292685 -0.01537353  0.04262422  0.52141552
   0.17591167 -0.10564692 -0.00466798 -0.04830423 -0.06950972 -0.01739668
  -0.02023709 -0.0041024   1.16341657 -0.4370525  -0.17084608 -0.02270836
  -0.08720052 -0.70000496 -0.87853475 -0.25182076 -0.24666506 -0.06692488]]
Intercept (intercept_): [0.2147777]


In [31]:
# Feature having largest positive coefficient
largest_coef_idx = np.argmax(np.abs(lr.coef_[0]))
feature_name = data.feature_names[largest_coef_idx]
coef_value = lr.coef_[0][largest_coef_idx]
print(f"Feature with largest positive coefficient: {feature_name}")
print(f"Coefficient value: {coef_value}")

Feature with largest positive coefficient: mean radius
Coefficient value: 1.1720577132915744


In [32]:
# Features having negative coefficients
neg_coef_idxs = np.where(lr.coef_[0] < 0)[0]
for idx in neg_coef_idxs:
    print(f"{data.feature_names[idx]}: {lr.coef_[0][idx]}")

mean area: -0.010064204441570582
mean smoothness: -0.04849855528149605
mean compactness: -0.21908728689183923
mean concavity: -0.30751360737161426
mean concave points: -0.12802328034440846
mean symmetry: -0.08292685188826891
mean fractal dimension: -0.015373527855923394
area error: -0.10564691699535436
smoothness error: -0.004667979666954793
compactness error: -0.04830422844021728
concavity error: -0.06950972442830738
concave points error: -0.017396682141838014
symmetry error: -0.020237085617385644
fractal dimension error: -0.004102396530573341
worst texture: -0.43705249862455836
worst perimeter: -0.17084607524670023
worst area: -0.02270836080466849
worst smoothness: -0.08720052019135056
worst compactness: -0.7000049561467686
worst concavity: -0.8785347486357303
worst concave points: -0.25182075538529236
worst symmetry: -0.2466650589008951
worst fractal dimension: -0.06692487640667848


## Support Vector Classification

In [33]:
# Load the dataset
from sklearn.datasets import load_iris
data = load_iris()
X = data.data
Y = data.target
data = load_breast_cancer()
X = data. data
Y = data.target


In [34]:
n_samples, n_features = X.shape
n_classes = len(np.unique(Y))
print("Number of samples:", n_samples)
print("Number of features:", n_features)
print("Number of classes:", n_classes)

Number of samples: 569
Number of features: 30
Number of classes: 2


In [35]:
# Train Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42, stratify=Y)

In [38]:
# Standardize Features
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [39]:
# Train Linear SVM
svc_linear = SVC(kernel='linear', random_state=42)
svc_linear.fit(X_train, Y_train)

Y_pred_svc = svc_linear.predict(X_test)
accuracy_svc = svc_linear.score(X_test, Y_test)

print("Linear SVC accuracy:", accuracy_svc)

Linear SVC accuracy: 0.9824561403508771


In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Evaluate Liear SVM
acc_svc = accuracy_score(Y_test, Y_pred_svc)
cm_svc = confusion_matrix(Y_test, Y_pred_svc)
report_svc = classification_report(Y_test, Y_pred_svc)

print("Accuracy (SVC):", acc_svc)
print("Confusion Matrix (SVC):\n", cm_svc)
print("Classification Report (SVC):\n", report_svc)

Accuracy (SVC): 0.9824561403508771
Confusion Matrix (SVC):
 [[ 62   2]
 [  1 106]]
Classification Report (SVC):
               precision    recall  f1-score   support

           0       0.98      0.97      0.98        64
           1       0.98      0.99      0.99       107

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



In [43]:
# Train RBF kernel
svc_rbf = SVC(kernel='rbf', random_state=42)
svc_rbf.fit(X_train, Y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",False
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Evaluate RBF SVM
acc_svc = accuracy_score(Y_test, Y_pred_svc)
cm_svc = confusion_matrix(Y_test, Y_pred_svc)
report_svc = classification_report(Y_test, Y_pred_svc)

print("Accuracy (SVC):", acc_svc)
print("Confusion Matrix (SVC):\n", cm_svc)
print("Classification Report (SVC):\n", report_svc)

Accuracy (SVC): 0.9824561403508771
Confusion Matrix (SVC):
 [[ 62   2]
 [  1 106]]
Classification Report (SVC):
               precision    recall  f1-score   support

           0       0.98      0.97      0.98        64
           1       0.98      0.99      0.99       107

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



In [45]:
# Compare linear and RBF SVC on the same test set
Y_pred_rbf = svc_rbf.predict(X_test)

acc_rbf = accuracy_score(Y_test, Y_pred_rbf)
cm_rbf = confusion_matrix(Y_test, Y_pred_rbf)
report_rbf = classification_report(Y_test, Y_pred_rbf)

print("Linear SVC kernel:", svc_linear.kernel)
print("RBF SVC kernel:", svc_rbf.kernel)
print("Linear SVC accuracy:", accuracy_svc)
print("RBF SVC accuracy:", acc_rbf)
print()
print("Linear SVC support vectors per class:", svc_linear.n_support_)
print("RBF SVC support vectors per class:", svc_rbf.n_support_)
print()
print("Linear SVC confusion matrix:\n", cm_svc)
print("RBF SVC confusion matrix:\n", cm_rbf)
print()
print("Linear SVC classification report:\n", report_svc)
print("RBF SVC classification report:\n", report_rbf)

Linear SVC kernel: rbf
RBF SVC kernel: rbf
Linear SVC accuracy: 0.9824561403508771
RBF SVC accuracy: 0.9766081871345029

Linear SVC support vectors per class: [49 42]
RBF SVC support vectors per class: [49 42]

Linear SVC confusion matrix:
 [[ 62   2]
 [  1 106]]
RBF SVC confusion matrix:
 [[ 62   2]
 [  2 105]]

Linear SVC classification report:
               precision    recall  f1-score   support

           0       0.98      0.97      0.98        64
           1       0.98      0.99      0.99       107

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

RBF SVC classification report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97        64
           1       0.98      0.98      0.98       107

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       

In [46]:
c_values = [0.1, 1, 10, 100]
accuracy_by_c = {}

for C in c_values:
    svc_tuned = SVC(kernel='linear', C=C, random_state=42)
    svc_tuned.fit(X_train, Y_train)
    y_pred_tuned = svc_tuned.predict(X_test)
    accuracy_by_c[C] = accuracy_score(Y_test, y_pred_tuned)

for C, acc in accuracy_by_c.items():
    print(f"C = {C}: accuracy = {acc:.4f}")


C = 0.1: accuracy = 0.9708
C = 1: accuracy = 0.9825
C = 10: accuracy = 0.9532
C = 100: accuracy = 0.9415
